export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const FETCH_BUILDINGS_ERROR = 'FETCH_BUILDINGS_ERROR'

export const ADD_BUILDINGS = 'ADD_BUILDINGS'
export const ADD_BUILDINGS_SUCCESS = 'ADD_BUILDINGS_SUCCESS'
export const ADD_BUILDINGS_ERROR = 'ADD_BUILDINGS_ERROR'

export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS'
export const UPDATE_BUILDINGS_SUCCESS = 'UPDATE_BUILDINGS_SUCCESS'
export const UPDATE_BUILDINGS_ERROR = 'UPDATE_BUILDINGS_ERROR'

export const DETAIL_BUILDINGS = 'DETAIL_BUILDINGS'
export const DETAIL_BUILDINGS_SUCCESS = 'DETAIL_BUILDINGS_SUCCESS'
export const DETAIL_BUILDINGS_ERROR = 'DETAIL_BUILDINGS_ERROR'

export const DELETE_BUILDINGS = 'DELETE_BUILDINGS'
export const DELETE_BUILDINGS_SUCCESS = 'DELETE_BUILDINGS_SUCCESS'
export const DELETE_BUILDINGS_ERROR = 'DELETE_BUILDINGS_ERROR'

export const FETCH_SLOTS_BUILDINGS = 'FETCH_SLOTS_BUILDINGS'
export const FETCH_SLOTS_BUILDINGS_SUCCESS = 'FETCH_SLOTS_BUILDINGS_SUCCESS'
export const FETCH_SLOTS_BUILDINGS_ERROR = 'FETCH_SLOTS_BUILDINGS_ERROR'

export const ADD_SLOT_BUILDINGS = 'ADD_SLOT_BUILDINGS'
export const ADD_SLOT_BUILDINGS_SUCCESS = 'ADD_SLOT_BUILDINGS_SUCCESS'
export const ADD_SLOT_BUILDINGS_ERROR = 'ADD_SLOT_BUILDINGS_ERROR'

export const UPDATE_SLOT_BUILDINGS = 'UPDATE_SLOT_BUILDINGS'
export const UPDATE_SLOT_BUILDINGS_SUCCESS = 'UPDATE_SLOT_BUILDINGS_SUCCESS'
export const UPDATE_SLOT_BUILDINGS_ERROR = 'UPDATE_SLOT_BUILDINGS_ERROR'

export const DETAIL_SLOT_BUILDINGS = 'DETAIL_SLOT_BUILDINGS'
export const DETAIL_SLOT_BUILDINGS_SUCCESS = 'DETAIL_SLOT_BUILDINGS_SUCCESS'
export const DETAIL_SLOT_BUILDINGS_ERROR = 'DETAIL_SLOT_BUILDINGS_ERROR'

export const DELETE_SLOT_BUILDINGS = 'DELETE_SLOT_BUILDINGS'
export const DELETE_SLOT_BUILDINGS_SUCCESS = 'DELETE_SLOT_BUILDINGS_SUCCESS'
export const DELETE_SLOT_BUILDINGS_ERROR = 'DELETE_SLOT_BUILDINGS_ERROR'
